/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing.ui;

import javax.swing.JOptionPane;
import swing.dao.HomestayDao;
import swing.dao.UserDao;
import swing.helpers.DataValidator;
import swing.helpers.MessageDialogHelper;
import swing.helpers.SharedData;
import swing.model.Homestay;
import swing.model.User;

/**
 *
 * @author Emi Tiramis
 */
public class AccountPanel extends javax.swing.JPanel {

    public User u = SharedData.u;

    /**
     * Creates new form AccountPanel
     */
    public AccountPanel() {
        initComponents();
        showInformation();
    }

    private void clearTxt() {
    }

    private void showInformation() {
        setEditablePanel(false);
        txtTelephone.setText(u.getTelephone());
        txtFirstName.setText(u.getFirstName());
        txtLastName.setText(u.getLastName());
        txtAddress.setText(u.getAddress());
        txtCountry.setText(u.getCountry());
        txtSex.setText((u.getSex() == 1) ? "Male" : "Female");
    }

    private void setEditablePanel(boolean state) {
        txtTelephone.setEditable(state);
        txtFirstName.setEditable(state);
        txtLastName.setEditable(state);
        txtAddress.setEditable(state);
        txtCountry.setEditable(state);
//        txtSex.setEditable(state);
//        txtPassword.setEditable(state);
//        txtVerifyPassword.setEditable(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        txtVerifyPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        kGradientPanel1.setkEndColor(new java.awt.Color(63, 120, 208));
        kGradientPanel1.setkStartColor(new java.awt.Color(39, 56, 83));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Verify password:");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telephone:");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First name:");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last name:");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address:");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Country:");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sex:");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        txtTelephone.setEditable(false);
        kGradientPanel1.add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 380, -1));

        txtFirstName.setEditable(false);
        kGradientPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 380, -1));

        txtLastName.setEditable(false);
        kGradientPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 380, -1));

        txtAddress.setEditable(false);
        kGradientPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 380, -1));

        txtCountry.setEditable(false);
        kGradientPanel1.add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 380, -1));

        txtSex.setEditable(false);
        kGradientPanel1.add(txtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 80, -1));
        kGradientPanel1.add(txtVerifyPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 380, -1));
        kGradientPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 380, -1));

        btnEdit.setText("Edit information");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, -1, -1));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/ui/images/icons8_male_user_100px.png"))); // NOI18N
        kGradientPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 190, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        setEditablePanel(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtFirstName, sb, "Missing first name");
        DataValidator.validateEmpty(txtLastName, sb, "Missing first name");
        DataValidator.validateEmpty(txtAddress, sb, "Missing address");
        DataValidator.validateEmpty(txtCountry, sb, "Missing country");
        DataValidator.validateEmpty(txtTelephone, sb, "Missing telephone");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(null, sb.toString(), "Error");
            return;
        }
        try {
            User u1 = new User();
            u1.setFirstName(txtFirstName.getText());
            u1.setLastName(txtLastName.getText());
            u1.setAddress(txtAddress.getText());
            u1.setCountry(txtCountry.getText());
            u1.setSex(u.getSex());
            u1.setTelephone(u.getTelephone());
            if (checkPassword() == 2){
                u1.setPassword(String.valueOf(txtPassword.getPassword()));
            } else if (checkPassword() == 0){
                u1.setPassword(u.getPassword());
            }
            UserDao dao = new UserDao();
            if (checkPassword() != 1) {
                if (dao.updateUser(u1)) {
                    MessageDialogHelper.showMessageDialog(null, "Saved", "Information");
                } else {
                    MessageDialogHelper.showConfirmDialog(null, "Cannot saved", "Warning");
                }
            } else {
                MessageDialogHelper.showMessageDialog(null, "Password doesn't match", "Information");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(null, e.getMessage(), "Error");
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private int checkPassword(){
        String pass = String.valueOf(txtPassword.getPassword());
        String verifiedPass = String.valueOf(txtVerifyPassword.getPassword());
        if (txtPassword.getPassword().length == 0){
            return 0;
        } else{
            if (!pass.equals(verifiedPass)){
                return 1;
            } else return 2;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JPasswordField txtVerifyPassword;
    // End of variables declaration//GEN-END:variables
}
